object_type: global_settings
overrides:
    "xmla.auth.token.enabled": true
    "xmla.discover.properties.daxdialect": tabular
    "query.result.max_rows": 300000
    "query.factless.ignoreincidentalfilter": false
